### ISSUE TITLE
Support polling state

### ISSUE THREAD

**Issue by boehser-enkel** [benzman81/homebridge-http-webhooks#72]
Hi,

is it possible to get an actual state of a device?

greetz
boehser enkel

**Comment by benzman81** [comment]
See here, but not supported for everything. https://github.com/benzman81/homebridge-http-webhooks/blob/master/README.md#retrieve-state

**Comment by boehser-enkel** [comment]
No want the plugin to get the state of the device to display the switch correctly

**Comment by benzman81** [comment]
Ah ok, I think I got you. That would only be possible by constantly polling the state of the device. I dont think that is a good idea.

**Comment by boehser-enkel** [comment]
There are plugins that do this. e.g. Broadlink RM. You could get the state at a certain interval or just when home pulls the actual state

**Comment by benzman81** [comment]
@boehser-enkel I know that this is possible and many plugins use this. But it is still a bad idea to poll for some states. For now, I decided to only follow the push / web hook mechanism, but feel free to provide a pull request.

**Comment by tritter** [comment]
@boehser-enkel Try my branch I think that should solve the issue. I also wanted to pull the switch state... https://github.com/benzman81/homebridge-http-webhooks/pull/108

**Comment by benzman81** [comment]
@tritter for switches this is supported since 0.1.0.

**Comment by benzman81** [comment]
Anyway, constant polling state is still not a good idea  ;-)
